Tweak Neo4j config to fix OutOfMemoryError
Attempts to fix:

java.lang.OutOfMemoryError: GC overhead limit exceeded

Refs https://github.com/neo4j/neo4j/issues/9209

From https://neo4j.com/docs/operations-manual/3.2/performance/#page-cache-sizing

You can determine the total memory needed for the page cache by summing up the sizes of
the NEO4J_HOME/data/databases/graph.db/*store.db* files and adding 20% for growth.

Hence, seems that 512m is sufficient for page cache.


Former-commit-id: 3f8dd90941384e94fef428dce0cc1c0d6d0c2bc7